site_theme: "air"              # Academic Pages skin: "default" or "air"
minimal_mistakes_skin: "air"   # Optional MM skin key (harmless if unused)
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
  - jekyll-include-cache
whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
  - jekyll-include-cache
---
layout: splash
title: "Lucian Bessmer"
subtitle: "Higher-ed strategy · Institutional analysis · Data storytelling"
permalink: /
header:
  overlay_color: "#0B1220"
  overlay_filter: 0.25
  # overlay_image: /images/hero.jpg   # optional
excerpt: "I help universities make clear, defensible decisions with evidence and compelling visuals."
feature_row:
  - title: "Research"
    excerpt: "Writing, memos, and analysis."
    url: "/posts/"
    btn_label: "Read"
    btn_class: "btn--primary"
  - title: "Teaching"
    excerpt: "Courses, materials, and notes."
    url: "/portfolio/"
    btn_label: "View"
    btn_class: "btn--primary"
  - title: "Visualizations"
    excerpt: "Interactive tools that explain complex topics."
    url: "/viz/"
    btn_label: "Explore"
    btn_class: "btn--primary"
sidebar: false
---
{% include feature_row %}
