# Welcome to Jekyll!

# Basic Site Settings
locale                   : "en-US"
site_theme               : "air"   # Academic Pages supports "default" or "air"
minimal_mistakes_skin    : "air"   # Extra key (used by Minimal Mistakes directly)
title                    : "Lucian Bessmer, PhD"
title_separator          : "-"
name                     : &name "Lucian Bessmer, PhD"
description              : &description "Higher-ed scholarship, strategy, and institutional analysis."
url: "https://lucianbessmer.com"
baseurl: ""                        # empty for a root-level custom domain
repository: "LBUG53/bug.academicpages.github.io"

# Site Author
author:
  name: "Lucian Bessmer"
  avatar: "/images/avatar.jpg"     # add this file (square headshot)
  bio: "Strategy & analysis for universities; I turn messy data into decisions."
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "lucianbessmer@gmail.com"

# Publication Category
publication_category:
  Research:
    title: 'Scholarship'
  Teaching:
    title: 'Teaching'    
  Red Brick Analysts:
    title: 'Consulting'

# Site Settings
teaser                   :  
breadcrumbs              : false 
words_per_minute         : 160
future                   : true
read_more                : "disabled"
talkmap_link             : false
comments:
  provider               : 
  disqus:
    shortname            :
  discourse:
    server               : 
  facebook:
    appid                :
    num_posts            : 
    colorscheme          : 
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "gh-pages"
  commitMessage          : "New comment."
  filename               : comm
