# Welcome to Jekyll! — Minimal Mistakes / Academic Pages configuration

# Basic Site Settings
locale                   : "en-US"
site_theme               : "air"                # Academic Pages skin: "default" or "air"
minimal_mistakes_skin    : "air"                # MM skin key (harmless if unused)
title                    : "Lucian Bessmer, PhD"
title_separator          : "-"
name                     : &name "Home"
description              : &description "Higher-ed scholarship, history, and strategy."
url                      : "https://lucianbessmer.com"
baseurl                  : ""
repository               : "LBUG53/bug.academicpages.github.io"

# Site Author
author:
  name    : "Lucian Bessmer"
  avatar  : "/images/avatar_mountain.jpg"                # add this file (square headshot)
  bio     : "Higher Ed Scholar, Historian, and Strategist."
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:lucianbessmer@gmail.com"


# Publication Category
publication_category:
  scholarship:
    title: "Scholarship"
  teaching:
    title: "Teaching"
  consulting:
    title: "Engagement"

# Site Settings
teaser                   :                      
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
talkmap_link             : false
comments:
  provider               :
  disqus:
    shortname            :
  discourse:
    server               :
  facebook:
    appid                :
    num_posts            :
    colorscheme          :
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "gh-pages"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601"
atom_feed:
  hide                   : false
  path                   :

# SEO / Social
og_image                 : /images/favicon.png   # add this file (512×512 recommended)
og_description           :
social:
  type                   : Person
  name                   : "Lucian Bessmer"
  links:
    - "mailto:lucianbessmer@gmail.com"

# Analytics
analytics:
  provider               : "false"
  google:
    tracking_id          :

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding                 : "utf-8"
markdown_ext             : "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown                 : kramdown
highlighter              : rouge
lsi                      : false
excerpt_separator        : "\n\n"
incremental              : false

# Markdown Processing
kramdown:
  input                  : GFM
  hard_wrap              : false
  auto_ids               : true
  footnote_nr            : 1
  entity_output          : as_char
  toc_levels             : 1..6
  smart_quotes           : lsquo,rsquo,ldquo,rdquo
  enable_coderay         : false

# Collections
collections:
  teaching:
    output    : true
    permalink : /:collection/:path/
  publications:
    output    : true
    permalink : /:collection/:path/
  portfolio:
    output    : true
    permalink : /:collection/:path/
  talks:
    output    : true
    permalink : /:collection/:path/

# Defaults
defaults:
  - scope:
      path  : ""
      type  : posts
    values:
      layout         : single
      author_profile : true
      read_time      : true
      comments       : true
      share          : true
      related        : true
  - scope:
      path  : ""
      type  : pages
    values:
      layout         : single
      author_profile : false        # cleaner default for standalone pages
  - scope:
      path  : ""
      type  : teaching
    values:
      layout         : single
      author_profile : true
      share          : true
      comments       : true
  - scope:
      path  : ""
      type  : publications
    values:
      layout         : single
      author_profile : true
      share          : true
      comments       : true
  - scope:
      path  : ""
      type  : portfolio
    values:
      layout         : single
      author_profile : true
      share          : true
      comment        : true
  - scope:
      path  : ""
      type  : talks
    values:
      layout         : talk
      author_profile : true
      share          : true

# Sass/SCSS
sass:
  sass_dir : _sass
  style    : compressed

# Outputting
permalink : /:categories/:title/
timezone  : America/New_York

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
  - jekyll-include-cache

# Mimic GitHub Pages with --safe
whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
  - jekyll-include-cache

# Archives
category_archive:
  type : liquid
  path : /categories/
tag_archive:
  type : liquid
  path : /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# --- site author avatar (added by setup) ---
author:
  name: "Lucian Bessmer"
  avatar: "/images/avatar_mountain.jpg"
