# Minimal Mistakes / Academic Pages configuration

# Basic Site Settings
locale                   : "en-US"
site_theme               : "air"
minimal_mistakes_skin    : "air"
title                    : "Lucian Bessmer, PhD"
title_separator          : "-"
masthead_title           : "Home"          # navbar brand link text
name                     : &name "Home"
description              : &description "Higher-ed scholarship, history, and strategy."
url                      : "https://lucianbessmer.com"
baseurl                  : ""
repository               : "LBUG53/bug.academicpages.github.io"

# IMPORTANT: leave empty so nothing auto-prefixes
image_path               : ""

# Keep these as BARE FILENAMES so includes that prepend "/images/" don't double it
logo                     : "favicon.png"
og_image                 : "hero_looking_wide.jpg"

# Site Author (no avatar)
author:
  name    : "Lucian Bessmer"
  bio     : "Higher Ed Scholar, Historian, and Strategist."
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url : "mailto:lucianbessmer@gmail.com"

# Feature Row
feature_row:
  - title: "Scholarship"
    url: "/scholarship/"
    excerpt: "Book project, publications, conference talks, and works in progress."
  - title: "Teaching"
    url: "/portfolio/"
    excerpt: "Course syllabi and teaching philosophy."
  - title: "Higher Ed Issues"
    url: "/higheredissues/"
    excerpt: "Explaining higher ed issues the way I’d want them explained to me."

# Publication Category
publication_category:
  scholarship:
    title: "Scholarship"
  teaching:
    title: "Teaching"
  consulting:
    title: "Engagement"

# Site Settings
teaser                   :
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"

# SEO / Social
social:
  type                   : Person
  name                   : "Lucian Bessmer"
  links:
    - "mailto:lucianbessmer@gmail.com"

# Reading Files
include:
  - .htaccess
  - _pages
  - files

# Conversion
markdown                 : kramdown
highlighter              : rouge

# Collections
collections:
  teaching:
    output    : true
    permalink : /:collection/:path/
  publications:
    output    : true
    permalink : /:collection/:path/
  portfolio:
    output    : true
    permalink : /:collection/:path/
  talks:
    output    : true
    permalink : /:collection/:path/

# Defaults — no sidebars anywhere
defaults:
  - scope:
      path  : ""
      type  : posts
    values:
      layout         : single
      author_profile : false
      toc            : false
      toc_sticky     : false
  - scope:
      path  : ""
      type  : pages
    values:
      layout         : single
      author_profile : false
      toc            : false
      toc_sticky     : false
  - scope:
      path  : ""
      type  : teaching
    values:
      layout         : single
      author_profile : false
      toc            : false
      toc_sticky     : false
  - scope:
      path  : ""
      type  : publications
    values:
      layout         : single
      author_profile : false
      toc            : false
      toc_sticky     : false
  - scope:
      path  : ""
      type  : portfolio
    values:
      layout         : single
      author_profile : false
      toc            : false
      toc_sticky     : false
  - scope:
      path  : ""
      type  : talks
    values:
      layout         : talk
      author_profile : false
      toc            : false
      toc_sticky     : false

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
  - jekyll-redirect-from
